name: CombatLog
main: org.CombatLog.CombatLog
version: 1.0
author: Nullplague
description:  a combat log plugin for spigot servers!
api-version: 1.15
softdepend: [Citizens,PlaceholderAPI]
commands:
  combatLog:
      description: desactiva el plugin
      usage: /combatlog <enable|disable|changestate>
      permission: combatlog.command.states
      permission-message: No tienes permisos para ejecutar este comando.